title: Life finds a way
author: Rsiow
email: richie.siow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where did what come from? How? Who started it all?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
